In [2]:
import torch
import numpy as np
torch.manual_seed(7)

# 1.create a tensor
### directly from data
 * torch.tensor(data, dtype=None, device=None, requires_grad=False, pin_memory=False)

In [23]:
data = [[0.1, 2], [-2, 3], [0.5, 0.2]]
torch.tensor(data)

tensor([[ 0.1000,  2.0000],
        [-2.0000,  3.0000],
        [ 0.5000,  0.2000]])

### from numpy
 * torch.from_numpy(ndarray, dtype=None, device=None, requires_grad=False, pin_memory=False)

In [28]:
data = np.array(data)
torch.from_numpy(data)

tensor([[ 0.1000,  2.0000],
        [-2.0000,  3.0000],
        [ 0.5000,  0.2000]], dtype=torch.float64)

### from another tensor
The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.
 * torch.ones_like(input, dtype=None, layout=None, device=None, requires_grad=False)
 * torch.zeros_like(input, dtype=None, layout=None, device=None, requires_grad=False)

In [30]:
tensor = torch.from_numpy(data)
torch.ones_like(tensor)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [31]:
torch.zeros_like(tensor)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)

In [41]:
torch.full_like(tensor, 3.14159)

tensor([[3.1416, 3.1416],
        [3.1416, 3.1416],
        [3.1416, 3.1416]], dtype=torch.float64)

### with random or constant values
shape is a tuple of tensor dimensions. In the functions below, it determines the dimensionality of the output tensor
* torch.empty(shape)
* torch.ones(*size, out=None, dtype=None, layout=torch.strided, device=None, required_grad=False)
* torch.zeros(*size, out=None, dtype=None, layout=torch.strided, device=None, required_grad=False)
* torch.full(size, fill_value, out=None, dtype=None, layout=torch.strided, device=None, required_grad=False)
* torch.arange(start=0, end, step=1, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
* torch.linspace(start, end, steps=100, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
* torch.logspace(start, end, steps=100, base=10.0, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
* torch.eye(n, m=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)



In [34]:
shape = (2, 3,)
torch.rand(shape)

tensor([[0.5349, 0.1988, 0.6592],
        [0.6569, 0.2328, 0.4251]])

In [37]:
torch.empty(shape)

tensor([[0., 0., 0.],
        [0., 0., -0.]])

In [35]:
torch.ones(shape)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [36]:
torch.zeros(shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [40]:
torch.full(shape, 3)

tensor([[3, 3, 3],
        [3, 3, 3]])

In [43]:
torch.arange(1, 2.5, 0.5)

tensor([1.0000, 1.5000, 2.0000])

In [44]:
torch.linspace(-10, 10, 5)

tensor([-10.,  -5.,   0.,   5.,  10.])

In [45]:
torch.logspace(0.1, 1, 5)

tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])

In [50]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

###  according to probability distribution
* torch.normal(mean, std, out=None)
* 正态分布: torch.randn(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
* 均匀分布: torch.rand(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
* 均匀分布: torch.randint(low=0, high, size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False)
* 随机排列: torch.randperm(n, out=None, dtype=torch.int64, layout=torch.strided, device=None, requires_grad=False)
* 伯努利分布: torch.bernoulli(input, *, generator=None, out=None)



In [55]:
torch.normal(torch.arange(1., 11.), torch.arange(1, 0, -0.1))

tensor([-0.2514,  0.3043,  3.3566,  3.5052,  4.0550,  5.6841,  7.0085,  7.8919,
         9.1132, 10.0214])

In [149]:
torch.normal(torch.tensor(1.), torch.arange(1, 0, -0.1))

tensor([ 0.2239,  1.4996,  1.1819, -0.5354,  0.8123,  1.1935,  1.1532,  0.7853,
         0.7847,  0.7890])

In [157]:
torch.normal(torch.arange(1., 11.), torch.tensor(0.4))

tensor([0.9784, 3.1832, 2.9405, 4.5592, 5.2700, 5.6584, 7.1437, 7.6651, 9.0430,
        9.4740])

In [159]:
torch.normal(torch.tensor(-1.), torch.tensor(2))

tensor(-4.0019)

In [60]:
torch.normal(0, 1, (1, 4))

tensor([[ 0.4589, -0.1495,  2.2695, -0.0911]])

In [61]:
torch.randn(2, 3)

tensor([[ 0.9732, -1.1010, -0.7484],
        [ 1.9863, -0.2902, -2.4220]])

In [62]:
torch.rand(2, 3)

tensor([[0.1049, 0.5137, 0.2674],
        [0.4990, 0.7447, 0.7213]])

In [63]:
torch.randint(3, 10, (2, 2))

tensor([[9, 3],
        [4, 6]])

In [65]:
torch.randperm(8)

tensor([7, 4, 0, 1, 3, 2, 5, 6])

In [66]:
tensor = torch.empty(3, 3).uniform_(0, 1)
torch.bernoulli(tensor)

tensor([[0., 1., 1.],
        [0., 0., 0.],
        [0., 0., 1.]])

# 2.Attributes of a Tensor

In [3]:
tensor = torch.rand(3)
print(tensor.dtype)
print(tensor.shape)
print(tensor.device)

torch.float32
torch.Size([3])
cpu


# 3. tensor operation

### Standard numpy-like indexing and slicing:

In [47]:
tensor = torch.ones(4, 4)
print(tensor)
tensor[:, ::2] = 0
print(tensor)
tensor[:2, :] = 2
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 1., 0., 1.],
        [0., 1., 0., 1.],
        [0., 1., 0., 1.],
        [0., 1., 0., 1.]])
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [0., 1., 0., 1.],
        [0., 1., 0., 1.]])


In [48]:
print(tensor[-1, ...])

tensor([0., 1., 0., 1.])


### In-place operations

In [49]:
tensor.add_(1)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [1., 2., 1., 2.],
        [1., 2., 1., 2.]])

### Joining tensors 
* torch.cat(tensors, dim=0, out=None)
* torch.stack(tensors, dim=0, out=None)
* torch.chunk(input, chunks, dim=0)
* torch.split(tensor, split_size_or_sections, dim=0)

In [13]:
tensor = torch.randn(3, 2)
tensor

tensor([[ 0.9329, -0.9412],
        [ 0.5536, -0.6499],
        [-1.5436, -0.5975]])

In [14]:
torch.cat((tensor, tensor, tensor), 0)

tensor([[ 0.9329, -0.9412],
        [ 0.5536, -0.6499],
        [-1.5436, -0.5975],
        [ 0.9329, -0.9412],
        [ 0.5536, -0.6499],
        [-1.5436, -0.5975],
        [ 0.9329, -0.9412],
        [ 0.5536, -0.6499],
        [-1.5436, -0.5975]])

In [15]:
torch.cat((tensor, tensor, tensor), 1)

tensor([[ 0.9329, -0.9412,  0.9329, -0.9412,  0.9329, -0.9412],
        [ 0.5536, -0.6499,  0.5536, -0.6499,  0.5536, -0.6499],
        [-1.5436, -0.5975, -1.5436, -0.5975, -1.5436, -0.5975]])

In [16]:
torch.stack((tensor, tensor, tensor), 0)

tensor([[[ 0.9329, -0.9412],
         [ 0.5536, -0.6499],
         [-1.5436, -0.5975]],

        [[ 0.9329, -0.9412],
         [ 0.5536, -0.6499],
         [-1.5436, -0.5975]],

        [[ 0.9329, -0.9412],
         [ 0.5536, -0.6499],
         [-1.5436, -0.5975]]])

In [17]:
torch.stack((tensor, tensor, tensor), 1)

tensor([[[ 0.9329, -0.9412],
         [ 0.9329, -0.9412],
         [ 0.9329, -0.9412]],

        [[ 0.5536, -0.6499],
         [ 0.5536, -0.6499],
         [ 0.5536, -0.6499]],

        [[-1.5436, -0.5975],
         [-1.5436, -0.5975],
         [-1.5436, -0.5975]]])

In [18]:
torch.stack((tensor, tensor, tensor), 2)

tensor([[[ 0.9329,  0.9329,  0.9329],
         [-0.9412, -0.9412, -0.9412]],

        [[ 0.5536,  0.5536,  0.5536],
         [-0.6499, -0.6499, -0.6499]],

        [[-1.5436, -1.5436, -1.5436],
         [-0.5975, -0.5975, -0.5975]]])

### change shape
* torch.reshape(input, shape)
* torch.transpose(input, dim0, dim1)
* torch.squeeze(input, dim=None, out=None)
* torch.unsqueeze(input, dim, out=None)


In [22]:
torch.chunk(tensor, 3, 0)

(tensor([[ 0.9329, -0.9412]]),
 tensor([[ 0.5536, -0.6499]]),
 tensor([[-1.5436, -0.5975]]))

In [23]:
torch.chunk(tensor, 2, 1)

(tensor([[ 0.9329],
         [ 0.5536],
         [-1.5436]]),
 tensor([[-0.9412],
         [-0.6499],
         [-0.5975]]))

In [24]:
torch.split(tensor, 1, 0)

(tensor([[ 0.9329, -0.9412]]),
 tensor([[ 0.5536, -0.6499]]),
 tensor([[-1.5436, -0.5975]]))

In [26]:
torch.split(tensor, 1, 1)

(tensor([[ 0.9329],
         [ 0.5536],
         [-1.5436]]),
 tensor([[-0.9412],
         [-0.6499],
         [-0.5975]]))

In [27]:
torch.reshape(tensor, (2, 3))

tensor([[ 0.9329, -0.9412,  0.5536],
        [-0.6499, -1.5436, -0.5975]])

In [28]:
torch.transpose(tensor, 1, 0)

tensor([[ 0.9329,  0.5536, -1.5436],
        [-0.9412, -0.6499, -0.5975]])

In [29]:
tensor = torch.zeros(2, 3, 1)
tensor

tensor([[[0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.]]])

In [30]:
torch.squeeze(tensor)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [31]:
torch.unsqueeze(tensor, 0)

tensor([[[[0.],
          [0.],
          [0.]],

         [[0.],
          [0.],
          [0.]]]])

### index
* torch.index_select(input, dim, index, out=None)
* torch.masked_select(input, mask, out=None)


In [32]:
tensor = torch.randn((3, 4))
tensor

tensor([[ 2.1382,  0.3900, -0.9062,  0.8873],
        [-0.7923, -1.5249, -0.1997, -0.0821],
        [-1.0587,  0.3344, -0.7804,  0.0804]])

In [33]:
indices = torch.tensor([0, 2])
torch.index_select(tensor, 0, indices)

tensor([[ 2.1382,  0.3900, -0.9062,  0.8873],
        [-1.0587,  0.3344, -0.7804,  0.0804]])

In [34]:
mask = tensor.ge(0.5)
mask

tensor([[ True, False, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [35]:
torch.masked_select(tensor, mask)

tensor([2.1382, 0.8873])

### move to gpu

In [5]:
print(tensor.device)
if torch.cuda.is_available():
    tensor = tensor.to("cuda")
print(tensor.device)

cpu
cpu
