In [4]:
import torch
from torch import nn
from torch.nn import functional as F

In [10]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self, X):
        return X - X.mean()
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [14]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-3.7253e-09, grad_fn=<MeanBackward0>)

In [24]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-1.9219,  1.9253, -0.1480],
        [ 0.0547,  0.5474,  0.2449],
        [ 1.7857, -0.6009, -0.3395],
        [ 0.4680,  2.1530,  0.4235],
        [-0.7524,  1.2948,  0.3919]], requires_grad=True)

In [25]:
linear(torch.rand(2, 5))

tensor([[0.0000, 2.3421, 0.7965],
        [0.0000, 0.8161, 0.7846]])

In [26]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.0000],
        [2.4918]])