In [1]:
import torch
from torch import nn
from torch.nn import functional as F

## loading and saving tensors

In [4]:
X = torch.arange(4)
torch.save(X, 'file-x')
X

tensor([0, 1, 2, 3])

In [5]:
torch.load('file-x')

tensor([0, 1, 2, 3])

In [6]:
Y = torch.zeros(4)
torch.save([X, Y], 'file-xy')
Y

tensor([0., 0., 0., 0.])

In [7]:
torch.load('file-xy')

[tensor([0, 1, 2, 3]), tensor([0., 0., 0., 0.])]

## loading and saving model parameters

In [13]:
class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden = nn.Linear(20, 256)
        self.output = nn.Linear(256, 10)
    
    def forward(self, X):
        return self.output(F.relu(self.hidden(X)))
net = MLP()
X = torch.randn(2, 20)
Y = net(X)
torch.save(net.state_dict(), 'mlp.params')

In [15]:
clone = MLP()
clone.load_state_dict(torch.load('mlp.params'))
clone.eval()

MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)

In [16]:
Y_clone = clone(X)
Y == Y_clone

tensor([[True, True, True, True, True, True, True, True, True, True],
        [True, True, True, True, True, True, True, True, True, True]])